#!/bin/bash

# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu
setopt EXTENDED_GLOB

. "$DOTPATH"/etc/lib/func


: "prezto install" && {

  if [[ -d "${ZDOTDIR:-$HOME}/.zprezto" ]]; then
    log_pass "prezto: allready installed"
  else
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
  fi

  for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
    if [ ! -f  "${ZDOTDIR:-$HOME}/.${rcfile:t}" ]; then
      ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
    else
      log_pass "prezto: ${ZDOTDIR:-$HOME}/.${rcfile:t} already exists."
    fi
  done
}
