#!/bin/bash

get_os() {
  case "$(uname | awk '{print tolower($0)}')" in
      *'linux'*)
          if [ -f /etc/os-release ]; then
            . /etc/os-release
            echo $ID_LIKE
          else
            echo 'linux'
          fi
          ;;
      *'darwin'*) echo 'macos'   ;;
      *'bsd'*)    echo 'bsd'     ;;
      *)          echo 'unknown' ;;
  esac
}
