#!/bin/bash

# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu

. "$DOTFILES_ROOT/script/functions"

if ! is_exists "yay"; then
  log_fail "error: require yay"
  exit 1
fi

yay -S zsh-completions tmux tig
yay -S git-lfs
yay -S exa fd ripgrep rargs zoxide bat
yay -S fpp ghq fzf
yay -S rlwrap
yay -S git-delta

if ! [ -d "$HOME/.config/bat/themes" ] ; then
  mkdir -p "$HOME/.config/bat/themes"
  git clone https://github.com/thara/gray-matter.git $HOME/.config/bat/themes/ || :
fi

VIM_DIR=$DOTFILES_ROOT/.vim
mkdir -p $VIM_DIR/autoload

yay -S vim vim-plug
