#!/bin/bash

# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu

. "$DOTFILES_ROOT/script/functions"

: "Hombrew install" && {

  export HOMEBREW_NO_ANALYTICS=1

  if is_exists "brew"; then
    log_pass "Homebrew: already installed"
  else
    if ! is_exists "ruby"; then
        log_fail "error: require: ruby"
        exit 1
    fi

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    if is_exists "brew"; then
        brew doctor
    else
        log_fail "error: brew: failed to install"
        exit 1
    fi

    log_pass "brew: installed successfully"
  fi
}


: "Hombrew setup" && {

  export HOMEBREW_NO_AUTO_UPDATE=1

  brew analytics off

  brew list vim &>/dev/null || brew install vim
  brew list rename &>/dev/null || brew install rename
  brew list tree &>/dev/null || brew install tree
  brew list wget &>/dev/null || brew install wget
  brew list zsh &>/dev/null || brew install zsh
  brew list zsh-completions &>/dev/null || brew install zsh-completions

  brew list exa &>/dev/null || brew install exa
  brew list fd &>/dev/null || brew install fd
  brew list rg &>/dev/null || brew install rg

  brew list tig &>/dev/null || brew install tig
  brew list tmux &>/dev/null || brew install tmux
  brew list reattach-to-user-namespace &>/dev/null || brew install reattach-to-user-namespace
  brew list urlview &>/dev/null || brew install urlview

  brew list bat &>/dev/null || brew install bat
  brew list fpp &>/dev/null || brew install fpp
  brew list ghq &>/dev/null || brew install ghq
  brew list fzf &>/dev/null || brew install fzf

  brew list rlwrap &>/dev/null || brew install rlwrap
  brew list coreutils &>/dev/null || brew install coreutils

  brew list git &>/dev/null || brew install git
  homebrew_prefix=$(brew --prefix)

  if ! [ -f "$homebrew_prefix/bin/diff-highlight" ] ; then
    ln -sfnv ${homebrew_prefix}/share/git-core/contrib/diff-highlight/diff-highlight ${homebrew_prefix}/bin
  fi

  brew list git-lfs &>/dev/null || brew install git-lfs
  brew list git-now &>/dev/null || brew install git-now
  brew list github/gh/gh &>/dev/null || brew install github/gh/gh

  if ! [ -d "$HOME/.config/bat/themes" ] ; then
    mkdir -p $HOME/.config/bat/themes
    git clone https://github.com/thara/gray-matter.git $HOME/.config/bat/themes/ || :
  fi

  brew list gpg2 &>/dev/null || brew install gpg2
  brew list pinentry-mac &>/dev/null || brew install pinentry-mac

  brew list mergepbx &>/dev/null || brew install mergepbx

  brew list todo-txt &>/dev/null || brew install todo-txt

  if [ -n "$DOTFILES_CASK" ] ; then
    brew cask list 1password &>/dev/null || brew cask install 1password
    brew cask list google-japanese-ime &>/dev/null || brew cask install google-japanese-ime
    brew cask list omnidisksweeper &>/dev/null || brew cask install omnidisksweeper
    brew cask list slack &>/dev/null || brew cask install slack
    brew cask list discord &>/dev/null || brew cask install discord
    brew cask list google-chrome &>/dev/null || brew cask install google-chrome
    brew cask list dropbox &>/dev/null || brew cask install dropbox
    brew cask list visual-studio-code &>/dev/null || brew cask install visual-studio-code
    brew cask list karabiner-elements &>/dev/null || brew cask install karabiner-elements
    #brew cask list google-backup-and-sync &>/dev/null || brew cask install google-backup-and-sync
    #brew cask list handshaker &>/dev/null || brew cask install handshaker  # Android device manager
    brew cask list github &>/dev/null || brew cask install github
    brew cask list kindle &>/dev/null || brew cask install kindle
    #brew cask list virtualbox &>/dev/null || brew cask install virtualbox
    brew cask list docker &>/dev/null || brew cask install docker
    brew cask list jetbrains-toolbox &>/dev/null || brew cask install jetbrains-toolbox
    brew cask list hammerspoon &>/dev/null || brew cask install hammerspoon
    brew cask list alfred &>/dev/null || brew cask install alfred
    brew cask list dash &>/dev/null || brew cask install dash

    brew tap caskroom/fonts
    brew cask list font-myrica &>/dev/null || brew cask install font-myrica font-myricam
  fi
}


VIM_DIR=$DOTFILES_ROOT/.vim

mkdir -p $VIM_DIR/autoload


: "Install vim-plug" && {
  if ! [ -f "$VIM_DIR/autoload/plug.vim" ] ; then
    curl -fLo $VIM_DIR/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    log_pass "vim: Install vim-plug"
  fi
}

: "Install tmux-plugins" && {
  if ! [ -d "$HOME/.tmux/plugins/tpm" ] ; then
    mkdir -p $HOME/.tmux/plugins/
    git clone https://github.com/tmux-plugins/tpm $HOME/.tmux/plugins/tpm
  fi
}
