#!/bin/bash

# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu
setopt EXTENDED_GLOB

. "$DOTFILES_ROOT/script/functions"

: "prezto install" && {

  if [[ -d "$HOME/.zprezto" ]]; then
    log_pass "prezto: allready installed"
  else
    git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto"
  fi

  for rcfile in "$HOME"/.zprezto/runcoms/^README.md(.N); do
    if [ ! -f  "$HOME/.${rcfile:t}" ]; then
      ln -s "$rcfile" "$HOME/.${rcfile:t}"
    else
      log_pass "prezto: $HOME/.${rcfile:t} already exists."
    fi
  done
}

