#!/bin/bash

# Stop script if errors occur
trap 'echo Error: $0:$LINENO stopped; exit 1' ERR INT
set -eu

. "$DOTFILES_ROOT/script/functions"

: "Hombrew install" && {

  export HOMEBREW_NO_ANALYTICS=1

  if is_exists "brew"; then
    log_pass "Homebrew: already installed"
  else
    if ! is_exists "ruby"; then
        log_fail "error: require: ruby"
        exit 1
    fi

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    if is_exists "brew"; then
        brew doctor
    else
        log_fail "error: brew: failed to install"
        exit 1
    fi

    log_pass "brew: installed successfully"
  fi
}


: "Hombrew setup" && {

  export HOMEBREW_NO_AUTO_UPDATE=1

  brew analytics off
  brew update  # https://github.com/travis-ci/travis-ci/issues/8552#issuecomment-335430374

  brew list rename &>/dev/null || brew install rename
  brew list tree &>/dev/null || brew install tree
  brew list wget &>/dev/null || brew install wget
  brew list zsh &>/dev/null || brew install zsh
  brew list zsh-completions &>/dev/null || brew install zsh-completions
  brew list the_silver_searcher &>/dev/null || brew install the_silver_searcher
  brew list reattach-to-user-namespace &>/dev/null || brew install reattach-to-user-namespace
  brew list rlwrap &>/dev/null || brew install rlwrap

  brew list git &>/dev/null || brew install git
  homebrew_prefix=$(brew --prefix)
  ln -sfnv ${homebrew_prefix}/share/git-core/contrib/diff-highlight/diff-highlight ${homebrew_prefix}/bin

  brew list git-lfs &>/dev/null || brew install git-lfs
  brew list git-now &>/dev/null || brew install git-now
  brew list tig &>/dev/null || brew install tig --with-docs
  brew list tmux &>/dev/null || brew install tmux

  brew list ghq &>/dev/null || brew install ghq
  brew list peco &>/dev/null || brew install peco
  brew list fzf &>/dev/null || brew install fzf

  # https://github.com/Homebrew/homebrew-core/issues/1165
  # brew list pyenv &>/dev/null || brew install pyenv
  # pyenv global system
  # brew list vim &>/dev/null || brew install vim --with-python --with-lua --with-luajit --with-cscope --with-ruby --with-luajit --with-perl

  # https://github.com/sdegutis/mjolnir
  brew install lua
  mkdir -p /usr/local/etc/luarocks52
  echo 'rocks_servers = { "http://rocks.moonscript.org" }' >> /usr/local/etc/luarocks52/config-5.2.lua

  brew tap caskroom/cask
  brew cask list google-japanese-ime &>/dev/null || brew cask install google-japanese-ime
  brew cask list mjolnir &>/dev/null || brew cask install mjolnir
  brew cask list iterm2 &>/dev/null || brew cask install iterm2
  brew cask list macvim &>/dev/null || brew cask install macvim
  brew cask list macdown &>/dev/null || brew cask install macdown
  #brew cask install appcleaner  # Error: Download failed on Cask 'appcleaner' with message: Download failed: https://www.freemacsoft.net/downloads/AppCleaner_3.4.zip
  brew cask list omnidisksweeper &>/dev/null || brew cask install omnidisksweeper
  brew cask list slack &>/dev/null || brew cask install slack
  brew cask list virtualbox &>/dev/null || brew cask install virtualbox
  brew cask list vagrant &>/dev/null || brew cask install vagrant
  brew cask list google-chrome &>/dev/null || brew cask install google-chrome
  brew cask list dropbox &>/dev/null || brew cask install dropbox
  brew cask list atom &>/dev/null || brew cask install atom
  brew cask list visual-studio-code &>/dev/null || brew cask install visual-studio-code
  brew cask list google-cloud-sdk &>/dev/null || brew cask install google-cloud-sdk
  brew cask list karabiner-elements &>/dev/null || brew cask install karabiner-elements
  brew cask list google-backup-and-sync &>/dev/null || brew cask install google-backup-and-sync
  brew cask list handshaker &>/dev/null || brew cask install handshaker  # Android device manager
  brew cask list github &>/dev/null || brew cask install github
  brew cask list kindle &>/dev/null || brew cask install kindle
  brew cask list sequel-pro &>/dev/null || brew cask install sequel-pro
  brew cask list docker &>/dev/null || brew cask install docker

  brew tap caskroom/fonts
  brew cask install font-myrica font-myricam
}


: "Install mjolnir dependencies" && {

  if ! is_exists "luarocks"; then
      log_fail "error: require: luarocks"
      exit 1
  fi

  luarocks install --local mjolnir.hotkey
  luarocks install --local mjolnir.application
  luarocks install --local mjolnir.th.hints
  luarocks install --local mjolnir.fnutils
  luarocks install --local mjolnir.geometry
  luarocks install --local mjolnir.screen
  luarocks install --local mjolnir.keycodes
}


VIM_DIR=$DOTFILES_ROOT/.vim

mkdir -p $VIM_DIR/autoload


: "Install vim-plug" && {
  if ! [ -f "$VIM_DIR/autoload/plug.vim" ] ; then
    curl -fLo $VIM_DIR/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    log_pass "vim: Install vim-plug"
  fi
}
