#!/bin/bash
set -eu

GITHUB_URL=https://github.com/thara/dotfiles

if [ -z "${DOTFILES_ROOT:-}" ]; then
  DOTFILES_ROOT=~/src/github.com/thara/dotfiles; export DOTFILES_ROOT
fi

print_done() {
    printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

log_fail() {
  # red
  local open="\033["
  local close="${open}0m"
  printf "${open}1;31m$1${close}\n"
}

# Returns true if executable $1 exists in $PATH
is_exists() {
    which "$1" >/dev/null 2>&1
    return $?
}

download_dotfiles() {

    printf "Downloading dotfiles...\n"

    if [ -d "$DOTFILES_ROOT" ]; then
        log_fail "$DOTFILES_ROOT: already exists"
        exit 1
    fi

    if is_exists "git"; then
        git clone --recursive "$GITHUB_URL" "$DOTFILES_ROOT"
    else
        log_fail "git required"
        exit 1
    fi

    printf "\n" && print_done "Dotfiles downloaded"
}


links_dotfiles() {

    printf "Linking dotfiles...\n"

    if [ ! -d $DOTFILES_ROOT ]; then
        log_fail "$DOTFILES_ROOT: not found"
        exit 1
    fi

    cd "$DOTFILES_ROOT"
    make links && printf "\n" && print_done "Dotfiles links"
}


download_dotfiles && links_dotfiles
