#!/bin/bash

trap 'echo Error: $0: stopped; exit 1' ERR INT

. "$DOTFILES_ROOT"/script/functions

ERR=0
export ERR

for i in "$DOTFILES_ROOT"/script/tests/*_test
do
  bash "$i" || ERR=1
done


if [ -n "$(get_os)" ]; then
    for i in "$DOTFILES_ROOT"/script/tests/test_"$(get_os)"
    do
        [ -f "$i" ] || continue
        bash "$i" || ERR=1
    done
fi

[ "$ERR" = 1 ] && exit 1 || exit 0
