<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
  <meta name="author" content="Tomochika Hara">
  <title>%title% - thara's garden</title>
  <link rel="stylesheet" type="text/css" href="%root_path%css/neat.css">
  <link rel="stylesheet" type="text/css" href="%root_path%css/custom.css">
  <meta name="Hatena::Bookmark" content="nocomment" />
  <link rel="author" href="http://www.hatena.ne.jp/zetta1985/" />
  %pygments%
</head>
<body>
  <header>
    <h1>%title%</h1>
  </header>
  %content%
<footer>
  <small>
    Page created on %date%
    | Generated by <a href="https://github.com/vimwiki/vimwiki">VimWiki</a>
    | &copy; 2024 Tomochika Hara
  </small>
</footer>
</body>
</html>
