name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: {}
    strategy:
      matrix:
        os: [ubuntu-latest,  macos-latest]

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: "false"

      - name: Install stow for macos
        run: |
          brew install stow
        if: matrix.os == 'macos-latest'

      - name: Install stow for Ubuntu
        run: |
          sudo apt-get install -y stow
        if: matrix.os == 'ubuntu-latest'

      - name: Apply All
        run: make

