name: macOS

on: [push]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        make install
      env:
        DOTFILES_INSTALL_APPS: ""
    - name: Run tests
      run: make test
