name: macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: |
        make init
      env:
        DOTFILES_CASK: ""
    - name: Run tests
      run: make test
